services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  TYPO3\CMS\Core\:
    resource: '../Classes/*'

  Psr\EventDispatcher\EventDispatcherInterface:
    alias: TYPO3\CMS\Core\EventDispatcher\EventDispatcher
    public: true

  TYPO3\CMS\Core\DependencyInjection\EnvVarProcessor:
    tags: ['container.env_var_processor']

  TYPO3\CMS\Core\Configuration\SiteConfiguration:
    arguments:
      $configPath: "%env(TYPO3:configPath)%/sites"

  TYPO3\CMS\Core\Package\PackageManager:
    autoconfigure: false

  TYPO3\CMS\Core\Package\FailsafePackageManager:
    autoconfigure: false

  TYPO3\CMS\Core\Package\UnitTestPackageManager:
    autoconfigure: false

  TYPO3\CMS\Core\Http\MiddlewareDispatcher:
    autoconfigure: false

  TYPO3\CMS\Core\Database\Schema\SqlReader:
    public: true

  # EventListeners
  TYPO3\CMS\Core\Compatibility\Slot\PostInitializeMailer:
    tags:
      - { name: event.listener,
          identifier: 'legacy-slot',
          event: TYPO3\CMS\Core\Mail\Event\AfterMailerInitializationEvent }

  # Core caches, cache.core and cache.assets are injected as early
  # entries in TYPO3\CMS\Core\Core\Bootstrap and therefore omitted here
  cache.hash:
    class: TYPO3\CMS\Core\Cache\Frontend\FrontendInterface
    factory: ['@TYPO3\CMS\Core\Cache\CacheManager', 'getCache']
    arguments: ['hash']

  cache.pages:
    class: TYPO3\CMS\Core\Cache\Frontend\FrontendInterface
    factory: ['@TYPO3\CMS\Core\Cache\CacheManager', 'getCache']
    arguments: ['pages']

  cache.pagesection:
    class: TYPO3\CMS\Core\Cache\Frontend\FrontendInterface
    factory: ['@TYPO3\CMS\Core\Cache\CacheManager', 'getCache']
    arguments: ['pagesection']

  cache.runtime:
    class: TYPO3\CMS\Core\Cache\Frontend\FrontendInterface
    factory: ['@TYPO3\CMS\Core\Cache\CacheManager', 'getCache']
    arguments: ['runtime']

  cache.rootline:
    class: TYPO3\CMS\Core\Cache\Frontend\FrontendInterface
    factory: ['@TYPO3\CMS\Core\Cache\CacheManager', 'getCache']
    arguments: ['rootline']

  cache.imagesizes:
    class: TYPO3\CMS\Core\Cache\Frontend\FrontendInterface
    factory: ['@TYPO3\CMS\Core\Cache\CacheManager', 'getCache']
    arguments: ['imagesizes']

  cache.l10n:
    class: TYPO3\CMS\Core\Cache\Frontend\FrontendInterface
    factory: ['@TYPO3\CMS\Core\Cache\CacheManager', 'getCache']
    arguments: ['l10n']
